### ISSUE TITLE
only past day rewards visible

### ISSUE THREAD

**Issue by woody5577** [helium/hotspot-app#1103]
In the app version 3.8.3 (I´m an android user) there is the following information missing:
- when you go to your miner, then it is indipendently of 24h or 14d or 30d the awards only including yesterday visible. Todays awards are not been shown anymore.
- I would expect to see the awards of the current day too based on my local time. So for example if I login at 11:00 a.m. German time --> my expectation is to see the sum of today between 00:00 - 11:00 a.m. German time everywhere --> in the home function and in each miners selection 24h, 14d, 30d

Screenshot I cannot provide, sorry, this is not possible since the last app update

Samsung Galaxy S8 Model SM-G950F
Android version 9**Describe the bug**

**Comment by cokes518** [comment]
Hi Woody,

We are updating how the reward time buckets are displayed from the API and in the app for performance improvements. Moving forward (and you probably have seen this already), the app will report the previous completed UTC calendar day's rewards. This will be what the summary on the Home Screen will display. i.e. "Your 3 Hotspots have earned 0.5 HNT on Nov 28 UTC)". This will be in 3.8.4 (available soon).

On the Hotspot charts, we'll be removing the 24h chart because the API only reports hourly earnings on a completed UTC day. So any earnings after midnight UTC will not be reported (and will be 0) until the day is complete. Instead of worrying our users with 0 earnings, we decide to show a complete day instead. 

The 14D and 30D charts will show earnings each day/week, based on a UTC calendar day.
