### ISSUE TITLE
Helium app doesnt accept my 12 words %100 I am sure 

### ISSUE THREAD

**Issue by beykan1987** [helium/hotspot-app#1240]
I have 12 words but couldn't access my wallet and 11 devices. 
I am totally sure with 12 words because I got the screen photos.  At first I access my wallet with my 12 words I added a 1 device. Then, I added 10 more devices. 

Now I can not access to my wallet with those words. Please help me.

**Comment by hintoncraig1** [comment]
I'm the same and no one can sort it . 12 words in order it's mad as now my box is wasted should be away to access with authentication and link to the senscap panel to transfer or send funds .
This really needs to be looked at 

Any advice ? Or is it all gone and no way to start over with the miner ?

**Comment by cokes518** [comment]
There is no bug here. The 12 words represent the private key to your wallet account. Lose your 12 words, lose your HNT and Hotspots. There's no way to unlock the Hotspot to re-onboard it.

https://docs.helium.com/wallets/app-wallet/twelve-words

**Comment by wolfenhawke** [comment]
@beykan1987 are you using your actual 12 words?? Because it's not a bug if you are not.

**Comment by hintoncraig1** [comment]
You should look at using authenticator like sensecap has
12 words I've got my 12 recovery words but your app isn't having it .
I feel robbed as your app isn't fool proof

You can't even look at the words I'm implementing and say otherwise as I know they are the recovery words I'm putting in I keep everyone .

You could just be a scammer like the rest on discord

This needs to be looked at as authenticator something is better than what you have implemented .
12 words really ? Pants now I'm now down a miner and my miner was
doin it's job .

I can't even transfer it

I don't care about the wallet it's the miner that is more important .

Seriously that aspect of helium needs seriously looking at .

I've got my 12 words safe your app just won't accept them and there right as wrote down in order .

Prove to me they not ?


If I by a new miner then will the location be buggered If my late pear owl miner is offline and binned off .
And I make a new account use my location to re assert

I'll make sure photograph the words next timr to protect myself from the likes of scammers .

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
