### ISSUE TITLE
Incorrect assertion location affecting transmission scales

### ISSUE THREAD

**Issue by Mizzo1979** [helium/hotspot-app#1258]
![114210E7-913D-4FF8-85FA-16B19BDF3FCE](https://user-images.githubusercontent.com/100404898/155673243-dceace98-f526-4249-9113-332f6d990585.png)
![8A1617A1-0A74-44DF-9D3D-102DFD7639D8](https://user-images.githubusercontent.com/100404898/155673250-9fdd8456-7805-4424-856b-0cca938922c9.png)
![3D3B585A-B5B0-4446-945F-F617217E4577](https://user-images.githubusercontent.com/100404898/155673254-55585829-79d6-4a9d-a2ef-aefec11b688e.jpeg)
**Describe the bug**
Asserted location showing correctly in Helium app. Asserted location showing incorrectly on Helium explorer.

3 screen shots 

2 showing location within helium app

1 showing asserted location in helium explorer with yellow highlighting the actual hex the assertion should be in.

This has happened with 2 x hotspots 
1x Blurry Fuchsia Horse ( this has now been relocated)
1 x Interesting Red Dinosaur

**To Reproduce**

4. See error5. 

I FOLLOWED STANDARD ASSERTION PROCESS

 

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

- App Version [e.g. 3.3.0]

iPhone 12 Pro

**Additional context**
Can the network credit the insertion fees or assert the correct location?

**Comment by cokes518** [comment]
assert locations are snapped to the center of the nearest resolution 8 hexagon and that a resolution 8 hexagon has an area of 737.3276 m² with edges measuring 461.354684 meters.

https://docs.helium.com/wallets/app-wallet/hexagons/#:~:text=Remember%20that%20a%20resolution%208,resolution%2012%20to%20resolution%204).

that's why it appears off.

and no, the network does not credit assert fees.
