### ISSUE TITLE
App shows Transaction failed and executes them afterwards

### ISSUE THREAD

**Issue by WantClue** [helium/hotspot-app#1275]
**In die App Transactions of sending HNT are marked as "failed" and executed afterwards**

**To Reproduce**

1. Go to 'Helium App'
2. Click on 'Send HNT'
3. Scroll down to '-'

**Expected behavior**
Transaction should be marked as pending and executed afterwards

**Screenshots**
![WhatsApp Image 2022-03-26 at 23 56 19 (1)](https://user-images.githubusercontent.com/86001033/160259709-879689ba-b537-4c1a-95e9-272edbc5474e.jpeg)
![WhatsApp Image 2022-03-26 at 23 56 19](https://user-images.githubusercontent.com/86001033/160259710-c3500ea5-7698-4e40-b0e6-5a12200e1a23.jpeg)

**Smartphone (please complete the following information):**

- Device: [iPhone 12]
- OS: [iOS15.4]
- App Version [latest]

**Comment by cokes518** [comment]
we've seen this happen in the past where the consensus group will originally reject the transaction then processes it. there has been improvements to the transactions manager on the blockchain side that handles this so we shouldn't see this anymore.

since it's technically a blockchain issue and not an app issue, i'll be closing this.
