### ISSUE TITLE
Helium hotspot transfer - help me please

### ISSUE THREAD

**Issue by Berkmf** [helium/hotspot-app#1361]
Please help me. I made a mistake.

I gave the hotspot I own to a friend.

Instead of the wallet I want to transfer to, I wrote an account address contained in that wallet.

I mistakenly wrote Hotspot address instead of Wallet address. The transfer has taken place. But Wallet can't see it in the address, I can't reach it.

**Comment by Ryan-Goldstein** [comment]
Hotspot [Shiny Grape Penguin](https://explorer.helium.com/hotspots/112HzBBUDa5iETmZHaRdi87MPhY6BQpwJZTxWy2fjhWoZs1vZdrc) was transferred from wallet [133S8k4p2JEQ2eFt3ksSPH29N9QD1oAJ1HNqcncHrbF87Bx2wMc](https://explorer.helium.com/accounts/133S8k4p2JEQ2eFt3ksSPH29N9QD1oAJ1HNqcncHrbF87Bx2wMc) to wallet [11n6k8NHomrQ9U9y3bgzj3bxPAX2guXBw34vXNiNLhbtF3bPezq](https://explorer.helium.com/accounts/11n6k8NHomrQ9U9y3bgzj3bxPAX2guXBw34vXNiNLhbtF3bPezq) (which was not a wallet prior to the transfer).

11n6k8NHomrQ9U9y3bgzj3bxPAX2guXBw34vXNiNLhbtF3bPezq is the address of a hotspot, [Obedient Mustard Rooster](https://explorer.helium.com/hotspots/11n6k8NHomrQ9U9y3bgzj3bxPAX2guXBw34vXNiNLhbtF3bPezq), the owner of which is [14PfLi4a7vbH2BtD8gMLhSBvbVha65xDEdu14JhyqJyiMdXLCP4](https://explorer.helium.com/accounts/14PfLi4a7vbH2BtD8gMLhSBvbVha65xDEdu14JhyqJyiMdXLCP4) - I'm guessing that was the intended wallet destination.

A Helium Hotspot app update from February 2022 (version 3.11.0) added a check to make sure a hotspot transfer target is a valid wallet, so I'm guessing you're using a very old version of the app, prior to 3.11.0, without that check.

Unfortunately, since the transfer has gone through, there is no way to undo it, as it's on the immutable blockchain.

**Comment by Berkmf** [comment]
I can access my wallet information. I have passwords. It shouldn't be that simple. Only account will be defined to Wallet.

**Comment by Berkmf** [comment]
It is very insecure that the system is not a helper.

**Comment by Ryan-Goldstein** [comment]
The hotspot was transferred to a wallet that you don't own. The same would apply in a situation where you transfer a hotspot to a buyer's wallet; you would not be able to subsequently transfer it elsewhere. If you could, that system would be insecure.

**Comment by Ryan-Goldstein** [comment]
> 11n6k8NHomrQ9U9y3bgzj3bxPAX2guXBw34vXNiNLhbtF3bPezq ; This address belongs to me. A hotspot that I own. Obedient Mustard Rooster this hotspot wallet information is available, I can access it. There is no one else.

Owning a hotspot with a specific B58 has no bearing on a wallet with the same B58 address. This is not a matter of being able to prove that you own the hotspot to some authority. There is no authority with the ability to transfer hotspots from a wallet except that wallet's owner.

This works the same way that people have sent millions of dollars worth of Bitcoin to the wrong wallet address; that Bitcoin is lost forever, since there's no central authority who can reverse or modify transactions that have occurred on the blockchain.

**Comment by ivorsmorenburg** [comment]
I have the same problem. I can understand that if you transfer to a private address, the owner might control the funds. But if you send it to a non-compatible address on an exchange like Binance, there should be some way to recover it on their end. The blockchain’s immutability is important, but I also think there should be an emergency option for reversing such accidental transactions.

**Comment by Ryan-Goldstein** [comment]
> I have the same problem. I can understand that if you transfer to a private address, the owner might control the funds. But if you send it to a non-compatible address on an exchange like Binance, there should be some way to recover it on their end. The blockchain’s immutability is important, but I also think there should be an emergency option for reversing such accidental transactions.

The Binance address is a normal Solana address, and the hotspot's NFT could be transferred from there to any other Solana address, if Binance decides to do so. If you have the private key from Binance, you could even import it into the Helium Wallet app and use it like any other Helium wallet address.

It's a Solana address owned by Binance, so it's up to them.
