### ISSUE TITLE
Show "Unable to retrieve data" in diagnostic report when miner is busy

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#469]
There can be times that miner is busy and won't be populate data in a diagnostic report. Instead of showing `null` fields or `0` for block height, we can display `Miner busy - unable to retrieve data`

In this case, the Hotspot is fully synced and showing 0 causes panic for users. It's better to illustrate the true root cause.

Example:
```Hotspot: silly-animal-name
Hotspot Maker: Cal-Chip Connected Devices
Address: 11my3WFEWdX44rEoUmSk6CDmvArC7ZgjXsQtnKAZqg3CTDDqdpY
Connected to Blockchain:
Dialable:
Height: 0

**Comment by tyler-whitman** [comment]
Instead of saying `Miner busy - unable to retrieve data` maybe we can just say `not available` and then at the bottom we put a note such as `* Diagnostics may be unavailable before a hotspot is fully booted. Please try generating the diagnostic report again to retrieve the information.`

Then it gives users an action to take, because even if they see `Miner busy - unable to retrieve data`  they may just email in and wonder what to do.
