### ISSUE TITLE
Add Subnavigation to Hotspot page

### ISSUE THREAD

**Issue by cokes518** [helium/hotspot-app#521]
To improve accessibility to reduce strain, move commonly used actions into a new sub-navigation menu on the Hotspot tab. This includes Network map, search, and quick access to Hotspots (followed, and owned) in an easily scrollable horizontal list.

The subnav will show all hotspots (followed (sorted by date followed), then owned (sorted by earnings, high to low))

Followed Hotspots will have a flag icon + animal noun
Owned Hotspots will have online/offline status + animal noun

In the event that animal nouns collide, we can show the second word. i.e. Green Tortoise, Holographic Tortoise

**Comment by cokes518** [comment]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/19331274/116593483-fcefb380-a8d5-11eb-9b35-d02bd2c4b994.png">

**Comment by PeterMain** [comment]
<img width="531" alt="Screenshot 2021-06-18 at 11 47 22" src="https://user-images.githubusercontent.com/3613880/122549951-f6a2cb80-d02a-11eb-80dd-f85fecb41856.png">

This has actually been updated since this story began. Best reference for this is 3.4.0 Figma file

Essentially the hotspot shortcut bar pills indicate the same status that a hotspot would have on the _chosen map filter active_.

**Examples above explained**

Top: Owned/Followed Map filter active. Aardvark and Antelope are followed (thus go first in list). Owned Hotspots follow.

Middle: Transmit Value filter active. Lizard is being viewed (it has a middling value). We order worst Transmit values first.

Bottom: Witness Map filter active. Any hotspots in shortcut bar that are witnesses (fish) of the currently selected hotspot (lizard) are highlighted yellow.
