### ISSUE TITLE
Add witness validity column to discovery mode output.

### ISSUE THREAD

**Issue by jskoizumi** [helium/hotspot-app#629]
I've been using discovery mode with great success comparing different configurations. I've been inputting data into a spread sheet and manually going through each witness to check for validity based on RSSI and SNR. Like this:

<img width="1371" alt="Screen Shot 2021-05-30 at 9 38 46 PM" src="https://user-images.githubusercontent.com/20649937/120392475-42840f80-c2cc-11eb-8630-0c687b8d84c6.png">

I wanted to make a small request/suggestion for the output, would it be possible to have an additional column in the 'Share Details' report thats generated that would specify  valid/invalid based on the preceding RSSI and SNR?

Thank you!

**Comment by cokes518** [comment]
Hi @jskoizumi so glad to hear that discovery mode is helping you compare different configurations! I hear your suggestion. The tricky thing here is that the SNR and RSSI is reported back by the Hotspot that heard the packet (off-chain) and witness validity is decided by the blockchain (per poc v10). We'd effectively need to check results against two different systems and amalgamate.

Where did you get that RSSI vs SNR graph? If those SNR/RSSI pairs are set, then it should be relatively easy to figure out if responders are valid or invalid. Also to note that this will change with the incoming pocv11, so it might be worth reworking the logic for pocv11 instead of v10.
