### ISSUE TITLE
Wifi network cannot be forgotten

### ISSUE THREAD

**Issue by jurajpe** [helium/hotspot-app#922]
**Describe the bug**
Wifi settings not cleared from the miner after network to be forgotten.

**To Reproduce**

1. Connect the miner the very first time in one location using wifi. 
2. It is relayed because I cannot forward the ports. The miner is in my workplace.
3. We agreed to create a separate DMZ network for the miner but that must be connected using lan.
4. The DMZ has a different DHCP range, different external IP. 
5. All is setup, I made the miner to forget the wifi previously used.
6. For half an hour the miner is online and removed from relay. The dash shows only the LAN IP details.
7. After another half an hour the dash shows that the wifi is connected too. it showns both internal IPs lan and wifi. The external IP is the one from the wifi netwotk. 
8. As a result the setting do not work and miner is ofline.
9.  

**Expected behavior**
This would be that if I say to forget the wifi network settings via the app, it will forget it completely. For some reason it does not. 
I will most probabaly have to connect to the wifi and place a blank password to force it to fail to connect. and then delete it.

I would like to see more settings for network:
1. Ability to turn off the wifi in the miner
2. Ability to write a name of a hidden network, so I do not need to un-hide it to connect. This is not good because usually when I hide it back sometimes when the connection is interupted the network is not found. As it does not broadcast the SSID.
3. Fix the bug that the forget wifi network does not really forget it.

**Screenshots**
N/A

**Smartphone (please complete the following information):**

- Device: [iPhone SE 2020]
- OS: [e.g. iOS 14.6]
- App Version [e.g. 3.4.7]

**Additional context**
Generally more settings fort he network in the app. that I could setup the static IP setting for example so I do not need to use DHCP and MAC reservations.
Like now it is great for technically not savvy people, but add a advanced box so peps like me can actually resolve this kind of issues in 5 minutes.

Thank you very much!

**Comment by ranezinjo** [comment]
Same issues on wired! Can't forget the IP

**Comment by shawaj** [comment]
Think the issue here is the same as #602 perhaps? 

Basically you click to forget WiFi and it does forget it, but instead of going back to the WiFi page it asks for the password again. This is using an OG hotspot.

See screenshots below...
![Screenshot_20211001-234020_Helium](https://user-images.githubusercontent.com/3359418/135695103-ae3f1865-3028-4814-8fe0-aca337a17bd4.jpg)
![Screenshot_20211001-234024_Helium](https://user-images.githubusercontent.com/3359418/135695104-2c4d7e3e-08c0-44b0-8f42-40c452700f29.jpg)
![Screenshot_20211001-234030_Helium](https://user-images.githubusercontent.com/3359418/135695105-968d77dc-7144-4d16-917a-1e267c5c22e8.jpg)


![Screenshot_20211001-234014_Helium](https://user-images.githubusercontent.com/3359418/135695099-726174ab-87e6-449c-b3f2-2d72b3256984.jpg)
