### ISSUE TITLE
Transfer Hotspot not working

### ISSUE THREAD

**Issue by Spirtatu** [helium/hotspot-app#999]
Trying to transfer hotspot, any recommendations why I can't do it? 

![IMG_0016](https://user-images.githubusercontent.com/44212300/138761855-72ddda86-abcd-4ce0-bd81-b5459ad622cf.jpg)

**Comment by edstewbob** [comment]
If a hotspot has been sold and is not active for a while there is no way to send it and transfer to a new owner since the location will likely change and there will not be any beaconing or witnessing until the new location is asserted by the new owner. The new owner should have the ability to setup and update the location information similar to what is done for a brand new hotspot. This inhibits the easy transfer of hotspots to new owners at new locations which can inhibit the growth of the Helium network.

**Comment by eiskop** [comment]
Any updates on this? Facing the same issue

**Comment by Spirtatu** [comment]
> Any updates on this? Facing the same issue

You need connect it to ethernet, so miner can sync to blockchain, after it synced should be no problem to transfer

**Comment by eiskop** [comment]
it seems to be stuck on 81.44% sync and won't budge.
